networks:
  devops:
    bootstrap: 2
    defaultNode: 3
    ensureScenarioPayerHbars: 10000
    nodes:
    - {account: 3, ipv4Addr: 35.196.138.70}
    scenarioPayer: 1043
    scenarios:
      sysFilesDown:
        evalMode: snapshot
        numsToFetch: [122]
      sysFilesUp:
        updates:
        - {num: 122, payer: 2}
  largeperfnet:
    bootstrap: 2
    defaultNode: 3
    ensureScenarioPayerHbars: 25
    nodes:
    - {account: 3, ipv4Addr: 34.95.133.166}
    scenarioPayer: 1065
    scenarios:
      sysFilesDown:
        evalMode: snapshot
        numsToFetch: [121]
      sysFilesUp:
        updates:
        - {num: 121, payer: 2}
  perfnet:
    bootstrap: 2
    defaultNode: 3
    ensureScenarioPayerHbars: 10000
    nodes:
    - {account: 3, ipv4Addr: 146.148.65.62}
    scenarioPayer: 6602
    scenarios:
      sysFilesDown:
        evalMode: snapshot
        numsToFetch: [121, 122]
      sysFilesUp:
        updates:
        - {num: 121, payer: 2}
        - {num: 122, payer: 2}
  integration:
    bootstrap: 2
    defaultNode: 3
    ensureScenarioPayerHbars: 10000
    nodes:
    - {account: 3, ipv4Addr: 34.74.191.8}
    scenarioPayer: 2415
    scenarios:
      sysFilesDown:
        evalMode: snapshot
        numsToFetch: [121]
      sysFilesUp:
        updates:
        - {num: 121, payer: 2}
  previewtestnet:
    bootstrap: 2
    defaultNode: 3
    ensureScenarioPayerHbars: 300
    nodes:
    - {account: 3, ipv4Addr: 35.231.208.148}
    - {account: 4, ipv4Addr: 35.199.15.177}
    - {account: 5, ipv4Addr: 35.225.201.195}
    - {account: 6, ipv4Addr: 35.247.109.135}
    scenarioPayer: 7786
    scenarios:
      feeSnapshots:
        appendToSnapshotCsv: true
        ignoreCostAnswer: true
        opsConfig: {bytecode: 7490, memoLength: 32}
        scheduleDesc: Bootstrap
        tinyBarsToOffer: 10000000000
      sysFilesDown:
        evalMode: snapshot
        numsToFetch: [122]
      sysFilesUp:
        updates:
        - {num: 122, payer: 2}
  stabletestnet:
    bootstrap: 50
    defaultNode: 3
    ensureScenarioPayerHbars: 300
    nodes:
    - {account: 3, ipv4Addr: 34.94.106.61}
    - {account: 4, ipv4Addr: 35.237.119.55}
    - {account: 5, ipv4Addr: 35.245.27.193}
    - {account: 6, ipv4Addr: 34.83.112.116}
    scenarioPayer: 48559
    scenarios:
      sysFilesDown:
        evalMode: snapshot
        numsToFetch: [121]
      sysFilesUp:
        updates:
        - {num: 121, payer: 50}
  mainnet:
    bootstrap: 950
    defaultNode: 3
    ensureScenarioPayerHbars: 100
    nodes:
    - {account: 5, ipv4Addr: 35.192.2.25}
    - {account: 6, ipv4Addr: 35.199.161.108}
    - {account: 14, ipv4Addr: 35.236.2.27}
    - {account: 15, ipv4Addr: 35.228.11.53}
    - {account: 3, ipv4Addr: 35.237.200.180}
    - {account: 4, ipv4Addr: 35.186.191.247}
    - {account: 7, ipv4Addr: 35.203.82.240}
    - {account: 8, ipv4Addr: 35.236.5.219}
    - {account: 10, ipv4Addr: 35.242.233.154}
    - {account: 11, ipv4Addr: 35.240.118.96}
    - {account: 12, ipv4Addr: 35.204.86.32}
    - {account: 13, ipv4Addr: 35.234.132.107}
    scenarioPayer: 45385
    scenarios:
      consensus: {persistent: 39286}
      contract:
        persistent: {bytecode: 39290, luckyNo: 42, num: 39291, source: Multipurpose.sol}
      crypto: {receiver: 45397, sender: 45396}
      file:
        persistent: {contents: MrBleaney.txt, num: 39283}
      sysFilesDown:
        evalMode: snapshot
        numsToFetch: [111]
  localhost:
    bootstrap: 2
    defaultNode: 3
    ensureScenarioPayerHbars: 100000
    nodes:
    - {account: 3, ipv4Addr: '127.0.0.1:50211'}
    scenarioPayer: 1001
    scenarios:
      consensus: {persistent: 1010}
      contract:
        persistent: {bytecode: 1007, luckyNo: 42, num: 1008, source: Multipurpose.sol}
      crypto: {receiver: 1003, sender: 1002}
      file:
        persistent: {contents: MrBleaney.txt, num: 1005}
  staging:
    bootstrap: 2
    defaultNode: 3
    ensureScenarioPayerHbars: 25
    nodes:
    - {account: 3, ipv4Addr: 35.237.182.66}
    - {account: 4, ipv4Addr: 35.245.226.22}
    - {account: 5, ipv4Addr: 34.68.9.203}
    - {account: 6, ipv4Addr: 34.83.131.197}
    - {account: 7, ipv4Addr: 34.94.236.63}
    - {account: 8, ipv4Addr: 35.203.26.115}
    - {account: 9, ipv4Addr: 34.77.3.213}
    - {account: 10, ipv4Addr: 35.197.237.44}
    - {account: 11, ipv4Addr: 35.246.250.176}
    - {account: 12, ipv4Addr: 34.90.117.105}
    - {account: 13, ipv4Addr: 35.200.57.21}
    - {account: 14, ipv4Addr: 34.92.120.143}
    - {account: 15, ipv4Addr: 34.87.47.168}
    scenarios:
      sysFilesDown:
        evalMode: snapshot
        numsToFetch: []
  stagingsm:
    bootstrap: 50
    defaultNode: 3
    ensureScenarioPayerHbars: 300
    nodes:
    - {account: 3, ipv4Addr: 104.196.48.231}
    - {account: 4, ipv4Addr: 35.245.168.191}
    - {account: 5, ipv4Addr: 35.192.152.7}
    - {account: 6, ipv4Addr: 35.203.163.15}
    scenarioPayer: 49542
    scenarios:
      consensus: {persistent: 39045}
      contract:
        persistent: {bytecode: 39042, luckyNo: 42, num: 39043, source: Multipurpose.sol}
      crypto: {receiver: 39038, sender: 39037}
      file:
        persistent: {contents: MrBleaney.txt, num: 39040}
  staginglg:
    bootstrap: 950
    defaultNode: 3
    ensureScenarioPayerHbars: 200
    nodes:
    - {account: 3, ipv4Addr: 35.237.208.135}
    - {account: 4, ipv4Addr: 35.236.222.232}
    - {account: 5, ipv4Addr: 34.68.193.194}
    - {account: 6, ipv4Addr: 34.83.9.37}
    - {account: 7, ipv4Addr: 34.94.94.224}
    - {account: 8, ipv4Addr: 35.203.83.23}
    - {account: 9, ipv4Addr: 34.77.100.22}
    - {account: 10, ipv4Addr: 35.242.186.231}
    - {account: 11, ipv4Addr: 35.246.141.12}
    - {account: 12, ipv4Addr: 34.90.168.32}
    - {account: 13, ipv4Addr: 35.200.13.38}
    - {account: 14, ipv4Addr: 34.92.103.251}
    - {account: 15, ipv4Addr: 35.198.224.198}
    scenarioPayer: 53186
    scenarios:
      consensus: {persistent: 39286}
      contract:
        persistent: {bytecode: 39290, luckyNo: 42, num: 39291, source: Multipurpose.sol}
      crypto: {receiver: 44771, sender: 44770}
      file:
        persistent: {contents: MrBleaney.txt, num: 39283}
      sysFilesDown:
        evalMode: snapshot
        numsToFetch: [121]
sleepMsBeforeNextNode: 2000
